cd $WORK/
mkdir SNP_reference_genome
cd $WORK
mkdir SNP-outputs
cd $WORK/SNP-outputs
mkdir length
mkdir trimmomatic
cd trimmomatic
mkdir trimlog
cd ../
mkdir bamfiles
mkdir snpEff
cd snpEff
mkdir snpEff-gene
mkdir snpEff-summary
mkdir filtered
cd ../
mkdir samfiles
mkdir flagsam
mkdir sortsam
mkdir depth
mkdir stats
mkdir picard
mkdir vcffilter-q
mkdir vcffilter-q-dp
mkdir bcfoutput
mkdir freebayesoutput
mkdir intersection
mkdir vcfbed
cd picard
mkdir picardlog
cd $WORK/SNP/
mkdir length
